name: Generate Availability Measure

description: 'Generates availability measure'

inputs:
  tag:
    required: false
    description: 'Git tag if present'
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install npm
      uses: actions/setup-node@v4

    - name: Install Sushi
      shell: bash
      run: npm install -g fsh-sushi

    - name: Set permissions
      shell: bash
      run: chmod +x availability/measure_shorthand/generate-availability-measure.sh

    - name: Run Availability generation
      shell: bash
      working-directory: ./availability/measure_shorthand
      run: ./generate-availability-measure.sh

    - name: Rename JSON (with tag if available) and zip
      shell: bash
      working-directory: ./availability/
      run: |
        TAG="${{ inputs.tag }}"
        if [[ -n "$TAG" ]]; then
          NEW_NAME="fdpg_availability_measure_${TAG}.json"
        else
          NEW_NAME="fdpg_availability_measure.json"
        fi
        mv Measure-CdsAvailabilityMeasure.json "$NEW_NAME"
        zip availability.zip "$NEW_NAME" stratum-to-context.json

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v4
      with:
        name: availability-zip
        path: availability/availability.zip