GECCO = "de.gecco 1.0.5"
GECCO_DIRECTORY = "de.gecco#1.0.5"
MII_CASE = "de.medizininformatikinitiative.kerndatensatz.fall 2024.0.0"
MII_DIAGNOSE = "de.medizininformatikinitiative.kerndatensatz.diagnose 2024.0.0"
MII_LAB = "de.medizininformatikinitiative.kerndatensatz.laborbefund 1.0.6"
MII_MEDICATION = "de.medizininformatikinitiative.kerndatensatz.medikation 2.0.0"
MII_PERSON = "de.medizininformatikinitiative.kerndatensatz.person 2024.0.0"
MII_PROCEDURE = "de.medizininformatikinitiative.kerndatensatz.prozedur 2024.0.0"
MII_SPECIMEN = "de.medizininformatikinitiative.kerndatensatz.biobank 1.0.1"
MII_CONSENT = "de.medizininformatikinitiative.kerndatensatz.consent 1.0.4"
DKTK = "de.dktk.oncology 1.3.0"
BBMRI = "bbmri.de"
ICU = "de.medizininformatikinitiative.kerndatensatz.icu 1.0.0"

GECCO_DATA_SET = "resources/core_data_sets/de.gecco#1.0.5/package"
MII_MEDICATION_DATA_SET = "resources/core_data_sets/de.medizininformatikinitiative.kerndatensatz.medikation#1.0.10" \
                          "/package"
SPECIMEN_VS = "https://www.medizininformatik-initiative.de/fhir/abide/ValueSet/sct-specimen-type-napkon-sprec"
