# ======================================================================================================================
#    Logging
# ======================================================================================================================
[loggers]
keys=root

[handlers]
keys=console

[formatters]
keys=standard

[logger_root]
level=NOTSET
handlers=console
propagate=1

[handler_console]
class=StreamHandler
level=INFO
formatter=standard
args=(sys.stdout,)

[formatter_standard]
format=%(asctime)s [%(levelname)s] %(module)s%(className)s::%(funcName)s:%(lineno)d - %(message)s
datefmt=%Y-%m-%dT%H:%M:%S
style=%
validate=1
class=common.util.log.ColorFormatter
