name: Build SQ2CQL
description: 'Builds and caches sq2cql CLI tool'

inputs:
  sq2cql-version:
    required: true
    description: 'Version of sq2cql library to use'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v5
      with:
        key: sq2cql-cli-${{ inputs.sq2cql-version }}
        path: tests/integration/cql/sq2cql-cli/target/sq2cql-cli.jar

    - uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        servers: |
          [{"id": "mii", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]
        properties: |
          [{"sq2cql.version": "${{ inputs.sq2cql-version }}"}]

    - name: Build JAR
      if: steps.restore-cache.outputs.cache-hit != 'true'
      working-directory: tests/integration/backend/sq2cql-cli
      shell: bash
      run: mvn package

    - name: Save cache
      if: steps.restore-cache.outputs.cache-hit != 'true'
      id: save-cache
      uses: actions/cache/save@v5
      with:
        key: sq2cql-cli-${{ inputs.sq2cql-version }}
        path: tests/integration/backend/sq2cql-cli/target/sq2cql-cli.jar