services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    ports:
      - '9200:9200'
      - '9300:9300'
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      node.name: es01
      cluster.name: elasticsearch
      xpack.security.enabled: false

  elastic-init:
    depends_on:
      - elastic
    image: ghcr.io/medizininformatik-initiative/dataportal-es-init:1.2
    environment:
      ES_HOST: elastic
      ONTO_GIT_TAG: v3.0.2-alpha
      MODE: mount # change this to mount when using own generated ontology
      LOCAL_PATH: /tmp/mounted_onto.zip
    volumes:
      - type: bind
        source: "../.tmp/elastic.zip"
        target: "/tmp/mounted_onto.zip"
        read_only: true