name: Integration Test Base Setup

on:
  push:

jobs:
  test_elastic_search:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup python 3 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install required python modules
      run: pip3 install -r requirements.txt

    - name: Generate Ontology
      id: generate_ontology # Add an id to refer to this step later
      uses: ./.github/workflows/generate_ontology

    - name: Access Generated ZIP Files
      run: |
        echo "Elastic.zip path: ${{ steps.generate_ontology.outputs.elastic_zip }}"
        echo "Mapping.zip path: ${{ steps.generate_ontology.outputs.mapping_zip }}"
        echo "Backend.zip path: ${{ steps.generate_ontology.outputs.backend_zip }}"
        ls -l ${{ steps.generate_ontology.outputs.elastic_zip }}
        ls -l ${{ steps.generate_ontology.outputs.mapping_zip }}
        ls -l ${{ steps.generate_ontology.outputs.backend_zip }}

    - name: Install testing pytest
      run: pip3 install pytest pytest-docker pytest-cov

    - name: Run tests
      run: |
        cd test/elastic_search
        pytest -v --cov

    - name: Upload Docker logs
      uses: actions/upload-artifact@v3
      with:
        name: docker_logs
        path: test/elastic_search/docker_logs