name: Integration Test Base Setup

on:
  push:
    tags-ignore:
      - '**'

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set locale
      run: |
        sudo apt-get update
        sudo apt-get install tzdata locales -y
        sudo locale-gen de_DE.UTF-8
        sudo localectl set-locale LANG="de_DE.UTF-8"
        export LANG="de_DE.UTF-8"
        sudo update-locale
        locale -a
        locale
        locale -c -k LC_NUMERIC
        localectl status

    - name: Setup python 3 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install required python modules
      run: pip3 install -r requirements.txt

    - name: Save secret to file
      id: certificates
      run: |
        echo "$PRIVATE_KEY" > private-key.pem
        echo "$SERVER_CERTIFICATE" > certificate.pem
        echo privateKey=$(readlink -f private-key.pem) >> "$GITHUB_OUTPUT"
        echo certificate=$(readlink -f certificate.pem) >> "$GITHUB_OUTPUT"
      env:
        SERVER_CERTIFICATE: ${{ secrets.FDPGPLUS_ONTO_SERVER_CERT }}
        PRIVATE_KEY: ${{ secrets.FDPGPLUS_ONTO_SERVER_KEY }}

    - name: Run ontology generation
      env:
        ONTOLOGY_SERVER_ADDRESS: ${{ secrets.FDPGPLUS_ONTO_SERVER_URL }}
        SERVER_CERTIFICATE: ${{ steps.certificates.outputs.certificate }}
        PRIVATE_KEY: ${{ steps.certificates.outputs.privateKey }}
      run: ./generate_full_ontology.sh --all

    - name: Install testing pytest
      run: pip3 install pytest pytest-docker pytest-cov

    - name: Run integration tests
      run: pytest test/integration -v --cov

    - name: Upload Docker logs
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: docker_logs
        path: test/integration/backend/docker_logs