name: Integration Test Base Setup

on:
  push:

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set locale
      uses: ./.github/actions/set-locale

    - name: Setup python 3 environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install required python modules
      run: pip3 install -r requirements.txt

    - name: Generate Ontology
      uses: ./.github/actions/generate-ontology

    - name: Install testing pytest
      run: pip3 install pytest pytest-docker pytest-cov

    - name: Run integration tests
      run: pytest test/integration -v --cov

    - name: Upload Docker logs
      uses: actions/upload-artifact@v4
      with:
        name: docker_logs
        path: test/integration/docker_logs

